### PR TITLE
[GUI-39] Display JSON as tree

### PR DESCRIPTION
**Pull request by AndreyKoltsov1997**
Creates an element which displays Mongoose configuration via JSON tree.

### CODE REVIEW

**Comment by akurilov** [comment]
Is it ready for a review?

**Comment by AndreyKoltsov1997** [comment]
@akurilov gradle files were added. Actually, I've merged updated 'master' and resolved all the conflicts. Everything should be testable now.

**Comment by AndreyKoltsov1997** [comment]
@akurilov The project's base has been updated with a solid .gitignore, thus I've updated this branch - no more 10k of C code. 
It's ready for review again.

**Comment by akurilov** [comment]
Tried to open in browser, the port 8080 is not listening

**Comment by AndreyKoltsov1997** [comment]
This PR doesn't affect anything related to port listening.

**Pull request merged**
