### PR TITLE
Gui 12 exposed port for server as cli argument

### PR DESCRIPTION
**Pull request by AndreyKoltsov1997**
You're able to send port as a command line argument to grade build script. 
If no arguments had been passed - the port will be set to default value which is 80. 

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

Signed-off-by: Andrey Koltsov <a99920641@gmail.com>

### CODE REVIEW

**Comment by veronikaKochugova** [comment]
I don't see comments for contributors in commits :(
like this: https://github.com/emc-mongoose/mongoose-storage-driver-pravega/pull/2/commits/5a57bfae66f8b6ab3adaaec30962053764cf3400

**Comment by AndreyKoltsov1997** [comment]
> I don't see comments for contributors in commits :(
> like this: [emc-mongoose/mongoose-storage-driver-pravega@5a57bfa](https://github.com/emc-mongoose/mongoose-storage-driver-pravega/commit/5a57bfae66f8b6ab3adaaec30962053764cf3400)

I've added the note to the pull request description. Is it enough or should I change commit's message? (As far as I know, I could change last commit's message)

**Comment by veronikaKochugova** [comment]
Now it is enough, but in the future it is necessary to include this message in each commit.

**Comment by veronikaKochugova** [comment]
otherwise I will not merge :)

**Pull request merged**
